#pragma once

#include "common/circuit/circuit.h"
#include "nph/net/net_np.h"
#include "nph/utils/prg_np.h"
#include "nph/utils/share.h"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <numeric>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace threepc::nph {

/**
 * OfflineEvaluator for the n-party semi-honest protocol with one helper.
 *
 * Parties 0..n-1 are compute parties.  Party n is the preprocessing helper.
 *
 * The offline phase establishes pairwise PRGs and then produces the
 * preprocessing material consumed by the online evaluator:
 *
 *   1. Beaver triples for kMul gates.
 *   2. Shuffle/unshuffle preprocessing for kShuffle and kUnshuffle gates.
 *
 * For multiplication, the helper communicates only the missing c-share to the
 * last compute party.  Shares of a and b, and all other c-shares, are sampled
 * from helper-party PRGs.
 *
 * For shuffle and unshuffle, the helper and every compute party derive the
 * party's local permutation and masks from their common PRG.  Permutations
 * are cached by perm_group_id during preprocessing, so all permutation gates in
 * the same group reuse the same local permutation.  Only the missing
 * correction share is sent to the final chain party: P_{n-1} for shuffle and
 * P0 for unshuffle.
 */
template <typename T>
class OfflineEvaluator {
 public:
  OfflineEvaluator(int pid, int num_compute_parties, NetNP& net)
      : pid_(pid), num_compute_parties_(num_compute_parties), net_(net) {
    if (num_compute_parties_ < 2)
      throw std::invalid_argument("NPH OfflineEvaluator: need at least two compute parties");
    if (pid_ < 0 || pid_ > helper_pid())
      throw std::invalid_argument("NPH OfflineEvaluator: invalid pid");
  }

  void run(const LevelOrderedCircuit& lc) {
    validateSupported(lc);

    // Establish helper-compute and compute-compute PRGs before any
    // preprocessing.  The compute-compute PRGs are kept for online input
    // sharing, while helper-compute PRGs are used here for preprocessing.
    pairwise_prg_.setup(pid_, num_compute_parties_, net_);

    const size_t num_triples =
        lc.count[static_cast<size_t>(GateType::kMul)];
    const std::vector<const Gate*> shuffle_gates = collectPermutationGates(lc);

    preproc_.triples.clear();
    preproc_.shuffles.clear();

    if (is_helper()) {
      if (num_triples != 0) helperGenerateTriples(num_triples);
    } else {
      preproc_.triples.resize(num_triples);
      preproc_.shuffles.reserve(shuffle_gates.size());

      if (num_triples != 0) computeGenerateTriples(num_triples);
    }

    // Shuffle preprocessing is generated by one unified routine.  The helper
    // side computes the global correction and sends the missing final share;
    // compute parties derive/store their local ShuffleGatePreproc entries.
    if (!shuffle_gates.empty()) generateShuffles(shuffle_gates);
  }

  Preprocessing<T> take_preprocessing() { return std::move(preproc_); }
  PairwisePRG take_pairwise_prg() { return std::move(pairwise_prg_); }

  const Preprocessing<T>& preprocessing() const { return preproc_; }

 private:
  struct ShufflePermGroup {
    size_t vec_size{0};

    // Used by the helper: all_perms[p] is the permutation pi_p of party P_p.
    std::vector<std::vector<size_t>> all_perms;

    // Used by compute parties: local_perm is this party's pi_pid.
    // All gates with the same perm_group_id point to the same vector.
    std::shared_ptr<const std::vector<size_t>> local_perm;
  };

  int pid_;
  int num_compute_parties_;
  NetNP& net_;
  Preprocessing<T> preproc_;
  PairwisePRG pairwise_prg_;

  static constexpr size_t kParallelPreprocThreshold = 8192;
  static constexpr size_t kParallelPermThreshold = 8192;

  int helper_pid() const { return num_compute_parties_; }
  int last_compute_pid() const { return num_compute_parties_ - 1; }
  bool is_helper() const { return pid_ == helper_pid(); }

  static std::vector<size_t> argsort(const std::vector<uint64_t>& keys) {
    std::vector<size_t> perm(keys.size());
    std::iota(perm.begin(), perm.end(), 0);
    std::sort(perm.begin(), perm.end(),
              [&](size_t a, size_t b) {
                if (keys[a] != keys[b]) return keys[a] < keys[b];
                return a < b;
              });
    return perm;
  }

  static std::vector<T> applyPerm(const std::vector<size_t>& perm,
                                  const std::vector<T>& v) {
    if (perm.size() != v.size()) {
      throw std::invalid_argument("NPH OfflineEvaluator::applyPerm: size mismatch");
    }
    for (size_t i = 0; i < perm.size(); ++i) {
      if (perm[i] >= v.size()) {
        throw std::runtime_error("NPH OfflineEvaluator::applyPerm: index out of range");
      }
    }

    std::vector<T> out(perm.size());
    #pragma omp parallel for if(perm.size() >= kParallelPermThreshold) schedule(static)
    for (long long ii = 0; ii < static_cast<long long>(perm.size()); ++ii) {
      const size_t i = static_cast<size_t>(ii);
      // Pull convention used by the circuit/evaluator: out[i] = v[perm[i]].
      out[i] = v[perm[i]];
    }
    return out;
  }

  static std::vector<T> applyInversePerm(const std::vector<size_t>& perm,
                                         const std::vector<T>& v) {
    if (perm.size() != v.size()) {
      throw std::invalid_argument("NPH OfflineEvaluator::applyInversePerm: size mismatch");
    }
    for (size_t i = 0; i < perm.size(); ++i) {
      if (perm[i] >= v.size()) {
        throw std::runtime_error("NPH OfflineEvaluator::applyInversePerm: index out of range");
      }
    }

    std::vector<T> out(perm.size());
    #pragma omp parallel for if(perm.size() >= kParallelPermThreshold) schedule(static)
    for (long long ii = 0; ii < static_cast<long long>(perm.size()); ++ii) {
      const size_t i = static_cast<size_t>(ii);
      // Inverse of out[i] = v[perm[i]] is out[perm[i]] = v[i].
      out[perm[i]] = v[i];
    }
    return out;
  }

  std::vector<size_t> samplePermutationWithParty(int party, size_t n) {
    std::vector<uint64_t> keys(n);
    pairwise_prg_.next<uint64_t>(party, keys.data(), keys.size());
    return argsort(keys);
  }

  std::vector<T> sampleVectorWithParty(int party, size_t n) {
    std::vector<T> v(n);
    pairwise_prg_.next<T>(party, v.data(), v.size());
    return v;
  }

  static bool isPermutationGate(GateType t) {
    return t == GateType::kShuffle || t == GateType::kUnshuffle;
  }

  static bool isInversePermutationGate(const Gate& g) {
    if (g.type == GateType::kShuffle) return false;
    if (g.type == GateType::kUnshuffle) return true;
    throw std::logic_error("NPH shuffle preprocessing: expected permutation gate");
  }

  static const std::vector<wire_t>& permGateIns(const Gate& g) {
    if (g.type == GateType::kShuffle)
      return static_cast<const ShuffleGate&>(g).ins;
    if (g.type == GateType::kUnshuffle)
      return static_cast<const UnshuffleGate&>(g).ins;
    throw std::logic_error("NPH shuffle preprocessing: expected permutation gate");
  }

  static int permGateGroupId(const Gate& g) {
    if (g.type == GateType::kShuffle)
      return static_cast<const ShuffleGate&>(g).perm_group_id;
    if (g.type == GateType::kUnshuffle)
      return static_cast<const UnshuffleGate&>(g).perm_group_id;
    throw std::logic_error("NPH shuffle preprocessing: expected permutation gate");
  }

  static std::vector<const Gate*> collectPermutationGates(
      const LevelOrderedCircuit& lc) {
    std::vector<const Gate*> gates;
    for (const auto& level : lc.gates_by_level) {
      for (const auto& gp : level) {
        if (isPermutationGate(gp->type)) {
          gates.push_back(gp.get());
        }
      }
    }
    return gates;
  }

  void validateSupported(const LevelOrderedCircuit& lc) const {
    for (const auto& level : lc.gates_by_level) {
      for (const auto& gp : level) {
        switch (gp->type) {
          case GateType::kInp: {
            const auto& g = static_cast<const InpGate&>(*gp);
            if (g.owner < 0 || g.owner >= num_compute_parties_) {
              throw std::runtime_error(
                  "NPH protocol: kInp supports only compute-party owners 0..n-1; "
                  "public/helper-owned kInp is not implemented");
            }
            break;
          }

          case GateType::kAdd:
          case GateType::kSub:
          case GateType::kCAdd:
          case GateType::kCSub:
          case GateType::kCMul:
          case GateType::kMul:
          case GateType::kRec:
          case GateType::kShuffle:
            break;

          case GateType::kUnshuffle: {
            const auto& g = static_cast<const UnshuffleGate&>(*gp);
            if (g.perm_group_id < 0) {
              throw std::runtime_error(
                  "NPH protocol: kUnshuffle requires an explicit non-negative perm_group_id");
            }
            break;
          }

          case GateType::kRecP: {
            const auto& g = static_cast<const FIn1Gate&>(*gp);
            if (g.owner < 0 || g.owner >= num_compute_parties_) {
              throw std::runtime_error(
                  "NPH protocol: kRecP target must be a compute party in 0..n-1");
            }
            break;
          }

          case GateType::kLocalPerm:
            throw std::runtime_error(
                "NPH protocol: kLocalPerm is not implemented yet");

          default:
            throw std::runtime_error("NPH protocol: unknown or invalid gate type");
        }
      }
    }
  }

  void helperGenerateTriples(size_t num_triples) {
    const int last = last_compute_pid();
    std::vector<T> last_c_shares(num_triples, T{});
    std::vector<std::vector<T>> sampled(static_cast<size_t>(num_compute_parties_));

    // PRG state is serial.  Draw each helper-party stream in exactly the same
    // order as the old per-triple loop: a, b, and c for non-final parties.
    for (int p = 0; p < num_compute_parties_; ++p) {
      const size_t fields_per_triple = (p == last) ? 2 : 3;
      auto& stream = sampled[static_cast<size_t>(p)];
      stream.resize(fields_per_triple * num_triples);
      pairwise_prg_.next<T>(p, stream.data(), stream.size());
    }

    #pragma omp parallel for if(num_triples >= kParallelPreprocThreshold) schedule(static)
    for (long long ii = 0; ii < static_cast<long long>(num_triples); ++ii) {
      const size_t i = static_cast<size_t>(ii);
      T a{};
      T b{};
      T c_share_sum{};

      // Sample all a_i and b_i from helper-compute PRGs. The corresponding
      // compute party samples the same values locally.
      for (int p = 0; p < num_compute_parties_; ++p) {
        const size_t fields_per_triple = (p == last) ? 2 : 3;
        const auto& stream = sampled[static_cast<size_t>(p)];
        const size_t base = fields_per_triple * i;
        const T a_p = stream[base];
        const T b_p = stream[base + 1];
        a += a_p;
        b += b_p;

        // Sample c_i non-interactively for all but the last compute party.
        if (p != last) {
          const T c_p = stream[base + 2];
          c_share_sum += c_p;
        }
      }

      const T c = a * b;
      last_c_shares[i] = c - c_share_sum;
    }

    // The only triple-generation communication: send c_L to the last compute
    // party in one batch. No other compute party receives triple data.
    net_.send_ring<T>(last_c_shares.data(), last_c_shares.size(), last);
    net_.flush(last);
  }

  void computeGenerateTriples(size_t num_triples) {
    const int helper = helper_pid();
    const int last = last_compute_pid();

    std::vector<T> received_last_c;
    if (pid_ == last) {
      received_last_c.resize(num_triples);
      net_.recv_ring<T>(received_last_c.data(), received_last_c.size(), helper);
    }

    const size_t fields_per_triple = (pid_ == last) ? 2 : 3;
    std::vector<T> sampled(fields_per_triple * num_triples);
    pairwise_prg_.next<T>(helper, sampled.data(), sampled.size());

    #pragma omp parallel for if(num_triples >= kParallelPreprocThreshold) schedule(static)
    for (long long ii = 0; ii < static_cast<long long>(num_triples); ++ii) {
      const size_t i = static_cast<size_t>(ii);
      const size_t base = fields_per_triple * i;
      preproc_.triples[i].a = AdditiveShare<T>(sampled[base]);
      preproc_.triples[i].b = AdditiveShare<T>(sampled[base + 1]);

      if (pid_ == last) {
        preproc_.triples[i].c = AdditiveShare<T>(received_last_c[i]);
      } else {
        preproc_.triples[i].c = AdditiveShare<T>(sampled[base + 2]);
      }
    }
  }

  ShufflePermGroup makeFreshShufflePermGroup(size_t n) {
    ShufflePermGroup group;
    group.vec_size = n;

    if (is_helper()) {
      group.all_perms.resize(static_cast<size_t>(num_compute_parties_));
      for (int p = 0; p < num_compute_parties_; ++p) {
        group.all_perms[static_cast<size_t>(p)] = samplePermutationWithParty(p, n);
      }
    } else {
      group.local_perm = std::make_shared<std::vector<size_t>>(
          samplePermutationWithParty(helper_pid(), n));
    }

    return group;
  }

  ShufflePermGroup& getOrCreateShufflePermGroup(
      int gid,
      size_t n,
      std::unordered_map<int, ShufflePermGroup>& cache) {
    auto it = cache.find(gid);
    if (it != cache.end()) {
      if (it->second.vec_size != n) {
        throw std::runtime_error(
            "NPH shuffle preprocessing: same perm_group_id reused with different vector size");
      }
      return it->second;
    }

    auto inserted = cache.emplace(gid, makeFreshShufflePermGroup(n));
    return inserted.first->second;
  }

  const std::vector<size_t>& permutationForParty(
      const Gate& gate,
      int party,
      std::unordered_map<int, ShufflePermGroup>& cache,
      ShufflePermGroup& fresh_group) {
    const size_t n = permGateIns(gate).size();

    ShufflePermGroup* group = nullptr;
    if (permGateGroupId(gate) >= 0) {
      group = &getOrCreateShufflePermGroup(permGateGroupId(gate), n, cache);
    } else {
      // Ungrouped shuffle: fresh independent permutations for this gate.
      // Store them in fresh_group so repeated calls for different parties in
      // this same gate reuse the same fresh material.
      if (fresh_group.vec_size == 0) fresh_group = makeFreshShufflePermGroup(n);
      group = &fresh_group;
    }

    if (!is_helper()) {
      throw std::logic_error(
          "NPH shuffle preprocessing: permutationForParty is helper-only");
    }
    if (party < 0 || party >= num_compute_parties_) {
      throw std::runtime_error("NPH shuffle preprocessing: invalid party id");
    }
    if (group->all_perms.size() != static_cast<size_t>(num_compute_parties_)) {
      throw std::runtime_error("NPH shuffle preprocessing: missing helper permutations");
    }
    return group->all_perms[static_cast<size_t>(party)];
  }

  std::shared_ptr<const std::vector<size_t>> localPermutationForGate(
      const Gate& gate,
      std::unordered_map<int, ShufflePermGroup>& cache,
      ShufflePermGroup& fresh_group) {
    const size_t n = permGateIns(gate).size();

    ShufflePermGroup* group = nullptr;
    if (permGateGroupId(gate) >= 0) {
      group = &getOrCreateShufflePermGroup(permGateGroupId(gate), n, cache);
    } else {
      // Ungrouped shuffle: fresh independent local permutation for this gate.
      if (fresh_group.vec_size == 0) fresh_group = makeFreshShufflePermGroup(n);
      group = &fresh_group;
    }

    if (is_helper()) {
      throw std::logic_error(
          "NPH shuffle preprocessing: localPermutationForGate is compute-only");
    }
    if (!group->local_perm) {
      throw std::runtime_error("NPH shuffle preprocessing: missing local permutation");
    }
    return group->local_perm;
  }

  void generateShuffles(const std::vector<const Gate*>& gates) {
    const int helper = helper_pid();
    const int last = last_compute_pid();

    std::vector<size_t> missing_delta_elems(static_cast<size_t>(num_compute_parties_), 0);
    for (const auto* g : gates) {
      const bool inverse = isInversePermutationGate(*g);
      const int final_party = inverse ? 0 : last;
      missing_delta_elems[static_cast<size_t>(final_party)] += permGateIns(*g).size();
    }

    std::vector<std::vector<T>> missing_delta_flat(
        static_cast<size_t>(num_compute_parties_));
    std::vector<T> received_missing_delta;

    if (is_helper()) {
      for (int p = 0; p < num_compute_parties_; ++p) {
        missing_delta_flat[static_cast<size_t>(p)].reserve(
            missing_delta_elems[static_cast<size_t>(p)]);
      }
    } else {
      const size_t my_missing = missing_delta_elems[static_cast<size_t>(pid_)];
      if (my_missing != 0) {
        received_missing_delta.resize(my_missing);
        net_.recv_ring<T>(received_missing_delta.data(), received_missing_delta.size(), helper);
      }
    }

    std::unordered_map<int, ShufflePermGroup> perm_cache;
    size_t received_delta_offset = 0;

    for (const Gate* gate_ptr : gates) {
      const Gate& gate = *gate_ptr;
      const bool inverse = isInversePermutationGate(gate);
      const int final_party = inverse ? 0 : last;
      const size_t n = permGateIns(gate).size();
      if (n == 0) {
        throw std::runtime_error("NPH shuffle preprocessing: empty shuffle gate");
      }

      // For perm_group_id == -1, this temporary object holds the fresh
      // per-gate permutation(s).  For grouped gates, perm_cache is used instead.
      ShufflePermGroup fresh_group;

      if (is_helper()) {
        std::vector<std::vector<T>> opening_masks(
            static_cast<size_t>(num_compute_parties_));
        std::vector<std::vector<T>> chain_masks(
            static_cast<size_t>(num_compute_parties_));

        std::vector<T> R(n, T{});
        for (int p = 0; p < num_compute_parties_; ++p) {
          // Generate/reuse pi_p before masks so that the helper and party P_p
          // consume their common PRG stream in the same order.
          (void)permutationForParty(gate, p, perm_cache, fresh_group);

          opening_masks[static_cast<size_t>(p)] = sampleVectorWithParty(p, n);
          chain_masks[static_cast<size_t>(p)] = sampleVectorWithParty(p, n);
          const auto& opening = opening_masks[static_cast<size_t>(p)];
          #pragma omp parallel for if(n >= kParallelPreprocThreshold) schedule(static)
          for (long long jj = 0; jj < static_cast<long long>(n); ++jj) {
            const size_t j = static_cast<size_t>(jj);
            R[j] += opening[j];
          }
        }

        // Delta is the result of applying the online permutation/masking chain
        // to R.  Shuffle runs P0 -> ... -> P_{n-1} with pi_p.  Unshuffle runs
        // P_{n-1} -> ... -> P0 with pi_p^{-1}.  Online applies the same chain
        // to X+R, so subtracting Delta leaves pi(X) or pi^{-1}(X).
        std::vector<T> delta = R;
        if (!inverse) {
          for (int p = 0; p < num_compute_parties_; ++p) {
            const std::vector<size_t>& pi =
                permutationForParty(gate, p, perm_cache, fresh_group);
            delta = applyPerm(pi, delta);
            const std::vector<T>& b = chain_masks[static_cast<size_t>(p)];
            #pragma omp parallel for if(n >= kParallelPreprocThreshold) schedule(static)
            for (long long jj = 0; jj < static_cast<long long>(n); ++jj) {
              const size_t j = static_cast<size_t>(jj);
              delta[j] += b[j];
            }
          }
        } else {
          for (int p = num_compute_parties_ - 1; p >= 0; --p) {
            const std::vector<size_t>& pi =
                permutationForParty(gate, p, perm_cache, fresh_group);
            delta = applyInversePerm(pi, delta);
            const std::vector<T>& b = chain_masks[static_cast<size_t>(p)];
            #pragma omp parallel for if(n >= kParallelPreprocThreshold) schedule(static)
            for (long long jj = 0; jj < static_cast<long long>(n); ++jj) {
              const size_t j = static_cast<size_t>(jj);
              delta[j] += b[j];
            }
          }
        }

        // Secret-share Delta.  All shares except the final chain party's share
        // are PRG-derived.  The helper sends only the missing final share:
        //   shuffle:   final party is P_{n-1}
        //   unshuffle: final party is P0
        std::vector<T> delta_sum(n, T{});
        for (int p = 0; p < num_compute_parties_; ++p) {
          if (p == final_party) continue;
          const std::vector<T> delta_p = sampleVectorWithParty(p, n);
          #pragma omp parallel for if(n >= kParallelPreprocThreshold) schedule(static)
          for (long long jj = 0; jj < static_cast<long long>(n); ++jj) {
            const size_t j = static_cast<size_t>(jj);
            delta_sum[j] += delta_p[j];
          }
        }

        auto& missing = missing_delta_flat[static_cast<size_t>(final_party)];
        const size_t base = missing.size();
        missing.resize(base + n);
        #pragma omp parallel for if(n >= kParallelPreprocThreshold) schedule(static)
        for (long long jj = 0; jj < static_cast<long long>(n); ++jj) {
          const size_t j = static_cast<size_t>(jj);
          missing[base + j] = delta[j] - delta_sum[j];
        }
      } else {
        ShuffleGatePreproc<T> pp;
        pp.perm_group_id = permGateGroupId(gate);
        pp.vec_size = n;
        pp.inverse = inverse;

        // The local permutation is preprocessing material.  Same group id means
        // this shared_ptr points to the same permutation vector as earlier gates
        // with that group id; masks below are always fresh per gate.
        pp.local_perm = localPermutationForGate(gate, perm_cache, fresh_group);

        pp.opening_mask_share = sampleVectorWithParty(helper, n);
        pp.chain_mask = sampleVectorWithParty(helper, n);

        if (pid_ == final_party) {
          pp.delta_share.assign(
              received_missing_delta.begin() + static_cast<std::ptrdiff_t>(received_delta_offset),
              received_missing_delta.begin() + static_cast<std::ptrdiff_t>(received_delta_offset + n));
          received_delta_offset += n;
        } else {
          pp.delta_share = sampleVectorWithParty(helper, n);
        }

        preproc_.shuffles.push_back(std::move(pp));
      }
    }

    if (is_helper()) {
      for (int p = 0; p < num_compute_parties_; ++p) {
        const auto& buf = missing_delta_flat[static_cast<size_t>(p)];
        if (!buf.empty()) {
          net_.send_ring<T>(buf.data(), buf.size(), p);
          net_.flush(p);
        }
      }
    }
  }
};

}  // namespace threepc::nph
